### ISSUE TITLE
Stuck at “Standby Mode”

### ISSUE THREAD

**Issue by numinosum** [PaulGoes/MIDIsonar#5]
Hello,
I got very enthousiastic about the MidiSonar and attempted to replicate it. Unfortunately I got stuck at the Standby Mode screen. The buttons are not responding, only one of the LEDs is flashing at startup. I am using an Arduino Leonardo and TeenOnArdu id. Could you please let me know where I might have been wrong? 
Another thing: one potentiometer is for the brightness of the lcd but what does the other one do?
Thanks a lot and thanks for uploading your work!
Regards,
Malen

**Comment by PaulGoes** [comment]
Hi Malen,

Nice to hear that someone is trying to build it too.

When I switch the MidiSonar on, it displays the text 'MIDIsonar   v0.9' on the first line of the LCD and then flashes the text 'by Paul Goes' three times on  the second line of the LCD.

After that it automatically goes to the Standby mode and displays the text 'MIDIsonar' on the first line of the LCD and the text 'Standby' on the second line of the LCD.

Then by pressing the buttonpin1 (=Analog A1 on pin nr 15) you can loop through the tree modes:
'Standby' --> 'Setup' --> 'Play' (and back again to Standy.

In Setup mode you can use the buttons buttonpin2 (=Analog A2 on pin 16) to go to the previous menu-item and buttonpin3 (=Analog A3 on pin 17) to go to the next menu-item. The currently selected menu-item is indicated by the underscore. When a menu-item is selected you can change the value of it by rotating the potentiometer (thats what that potentiometer is for: changing the values).

Hope that this helps.

**Comment by numinosum** [comment]
Hi again,

Thanks so much for your reply! It does help me to understand the structure and the sonar loads just as you described (so the setup and the screen work up to that point), however I still cannot get past the Standby Mode. The buttons simply do not respond. So I am wondering where I might be wrong. Do you think the Arduino version matters? I have a Leonardo as a TeeOnArdu board which makes it a class compliant usb-midi device. Tried setting it as a regular Leonardo too but it is all the same. I checked all my connections, still nothing. As I mentioned, only one of my LEDs flashes after reset. Where do you think I should look?

Can you confirm the specs of your components? I use 10kOhm pots and 10kOhm (brown, black, orange, gold) and 220 Ohm (red, red, brown, gold) resistors. Is the second pot actually an encoder?

I am new to Arduino as you can see so sorry if my questions sound a bit naive. Any help is much appreciated.
Best wishes,
Malen

**Comment by PaulGoes** [comment]
Hi Malen,

I've only used the Arduino Uno and never the Leonardo. What I see from various sites on the Internet, is that the Leonardo works a little different when using analog pins as digital pins. That is what MidiSonar does: the three digital buttons use analog pins: 'Button MODE SELECT' = A1, 'Button MENU PREV' = A2 and 'Button MENU NEXT' = A3.

On the Arduino UNO this maps as: A1 = pin 15, A2 = pin 16 and A3 = pin 17. 

But on the Arduino Leonardo this maps as: A1 = pin 19, A2 = pin 20 and A3 = pin 21 (if I interpret the information on Internet correctly).

This might cause your problems. It is using the wrong pin definitions. What you could try is to change the mapping of buttonPin1, buttonPin2 and buttonPin3 in the '/* initialize the push buttons */' section of the code to 19, 20 and 21 respectively.

Both pots are simple potentiometers and not rotary encoders. An endless rotary encoder for data entry would be more intuitive to use, but requires changes in the code. Maybe I will do that later, but for know a simple potentiometer works also.

Hope this helps!

**Comment by numinosum** [comment]
Brilliant!! It worked! 

Just as you presumed, the pin definitions needed to be changed to 19, 20 and 21 and it is now fully functional. Thank you so much!!

I still have to figure out how to make it work as a usb midi device so I am digging into code and libraries. If I manage I could upload my version here. But so far my problem is solved and I am verry grateful :)

Best wishes, 
Malen

**Comment by numinosum** [comment]
PS: I am interested in developing this project and perhaps adding additional features like cc controls or keys or even sensors to it. Please get in touch if you are too. My mail is actinplay@gmail.com . Best, Malen
